<?php

/**
 * Produse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Produse extends BaseProduse
{
    public function setUp()
    {
        parent::setUp();

        $this->hasOne('GalerieFoto as MainPhoto', array(
             'local' => 'id',
             'foreign' => 'produs_id'
            )
        );
        $this->hasOne('Categorii as Categorie', array(
             'local' => 'categorie_id',
             'foreign' => 'id'
            )
        );
    }
}